---
- name: Create directories
  file: path={{ item.path }} state=directory mode={{ item.mode }}
  with_items:
          - { path: "{{ hadoop_install_dir }}", mode: '0755' }

- name: Copying templated files (provisioning scripts/config)
  template: src={{ item.src }} dest="{{ hadoop_install_dir}}/{{ item.dest }}" mode=0744
  with_items:
          - { src: 'hadoop-config.sh.j2', dest: 'hadoop-config.sh' }
          - { src: 'provision-hadoop.sh.j2', dest: 'provision-hadoop.sh' }
          - { src: 'provision-master.sh.j2', dest: 'provision-master.sh' }
          - { src: 'provision-slave.sh.j2', dest: 'provision-slave.sh' }
          - { src: 'yarn-site.xml.j2', dest: 'yarn-site.xml' }

- name: Copying configuration/control scripts
  copy: src={{ item.file }} dest="{{ hadoop_install_dir }}/{{ item.file }}"  mode={{ item.mode }}
  with_items:
          - { file: 'container-executor.cfg', mode: '0644' }
          - { file: 'core-default.xml', mode: '0644' }
          - { file: 'core-site.xml', mode: '0644' }
          - { file: 'yarn-default.xml', mode: '0644'  }
          - { file: 'mapred-site.xml', mode: '0644'  }
          - { file: 'test-pi-yarn.sh', mode: '0744'  }
          - { file: 'restart-hadoop-master-daemons.sh', mode: '0744'  }
          - { file: 'restart-hadoop-slave-daemons.sh', mode: '0744'  }
